server:
  port: 7001

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:9003/eureka/,http://localhost:9002/eureka/,http://localhost:9001/eureka/

feign:
  hystrix:
    enabled: true