eureka:
  instance:
    hostname: eureka02
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9001/eureka/,http://localhost:9003/eureka/
server:
  port: 9002